# .github/workflows/build-and-deploy.yml
name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-and-deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    defaults:
      run:
        working-directory: frontend   # 👈 todo corre dentro de frontend/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Show Node & npm versions
        run: |
          node -v
          npm -v

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # Opcional: guarda el build para inspeccionarlo si algo falla en deploy
      - name: Upload build artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: warn
          retention-days: 7

      # 🔗 Prepara el link de Vercel (evita "Could not retrieve Project Settings")
      - name: Prepare Vercel link
        if: github.event_name != 'pull_request'
        run: |
          rm -rf .vercel
          mkdir -p .vercel
          printf '{"projectId":"%s","orgId":"%s"}' "${{ secrets.VERCEL_PROJECT_ID }}" "${{ secrets.VERCEL_ORG_ID }}" > .vercel/project.json
          echo "Created .vercel/project.json:"
          cat .vercel/project.json

      # 🚀 Deploy con la action oficial (usa @v25 y NO 'prod', sino 'vercel-args: --prod')
      - name: Deploy to Vercel
        if: github.event_name != 'pull_request'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}            # REQUIRED
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}          # REQUIRED (Team ID)
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # REQUIRED (Project ID prj_…)
          working-directory: frontend
          vercel-args: '--prod'
