name: semgrep-scan

on:
  push:
    paths:
      - '**/*.ts'
      - 'security/semgrep/**'
  pull_request:
    paths:
      - '**/*.ts'
      - 'security/semgrep/**'

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run semgrep scan
        id: semgrep
        run: |
          semgrep --config security/semgrep/nosql-injection.yml --json > semgrep-result.json || true
          cat semgrep-result.json

      - name: Fail on findings
        if: steps.semgrep.outcome == 'success' || always()
        run: |
          jq '.results | length as $n | if $n > 0 then ("Found " + ($n|tostring) + " semgrep findings" ) | error else echo "No findings" end' semgrep-result.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
